# Wisp Bash integration. Generated by wisp init bash.

if [[ $- == *i* ]]; then
  if (( BASH_VERSINFO[0] < 4 )); then
    printf '%s\n' 'wisp: Bash 4.0 or newer is required (macOS /bin/bash 3.2 does not expose READLINE_LINE/READLINE_POINT)' >&2
  elif [[ -z ${_WISP_BASH_LOADED:-} ]]; then
    export WISP_SESSION_ID="bash-${BASHPID:-$$}-${RANDOM}${RANDOM}"
    _WISP_BASH_LOADED=1
    _WISP_REQUEST_ID=0
    _WISP_LAST_STATE=''
    _WISP_RENDERED_BUFFER=''
    _WISP_RENDERED_CURSOR=0
    _WISP_PROMPT=''
    _WISP_RENDERED_PROMPT=''
    _WISP_RENDERED_COLUMNS=${COLUMNS:-80}
    _WISP_HISTORY_OFFSET=0
    _WISP_VIEWPORT_X=0
    _WISP_VIEWPORT_Y=0
    _WISP_PANE_COLUMNS=${COLUMNS:-80}
    _WISP_PANE_ROWS=${LINES:-24}
    _WISP_GRID_COLUMNS=${COLUMNS:-80}
    _WISP_GRID_ROWS=${LINES:-24}

    _wisp_bash_byte_length() {
      local LC_ALL=C
      _WISP_BYTE_LENGTH=${#1}
    }

    _wisp_bash_char_to_byte() {
      local text=$1 count=$2 prefix
      prefix=${text:0:count}
      _wisp_bash_byte_length "$prefix"
    }

    _wisp_bash_refresh_viewport() {
      local geometry
      if [[ -n ${ZELLIJ:-} ]] && geometry=$(command "${WISP_BIN:-wisp}" shell viewport 2>/dev/null); then
        eval "$geometry"
      else
        _WISP_VIEWPORT_X=0
        _WISP_VIEWPORT_Y=0
        _WISP_PANE_COLUMNS=${COLUMNS:-80}
        _WISP_PANE_ROWS=${LINES:-24}
        _WISP_GRID_COLUMNS=${COLUMNS:-80}
        _WISP_GRID_ROWS=${LINES:-24}
      fi
    }

    _wisp_bash_dismiss() {
      command "${WISP_BIN:-wisp}" shell dismiss \
        --session "$WISP_SESSION_ID" \
        --request-id "$_WISP_REQUEST_ID" \
        >/dev/null 2>&1 &
    }

    _wisp_bash_update() {
      local buffer=${READLINE_LINE-} point=${READLINE_POINT-0} state
      [[ ${READLINE_LINE+x} ]] || return 0
      if (( _WISP_PANE_COLUMNS != ${COLUMNS:-80} || _WISP_PANE_ROWS != ${LINES:-24} )); then
        _wisp_bash_refresh_viewport
      fi
      state="${_WISP_VIEWPORT_X}:${_WISP_VIEWPORT_Y}:${COLUMNS:-80}:${LINES:-24}:${point}:${_WISP_PROMPT}:${buffer}"
      [[ $state == "$_WISP_LAST_STATE" ]] && return 0
      _WISP_LAST_STATE=$state
      ((_WISP_REQUEST_ID += 1))
      command "${WISP_BIN:-wisp}" shell update \
        --session "$WISP_SESSION_ID" \
        --request-id "$_WISP_REQUEST_ID" \
        --buffer "$buffer" \
        --cursor "$point" \
        --cursor-unit bytes \
        --cwd "$PWD" \
        --prompt "$_WISP_PROMPT" \
        --columns "${COLUMNS:-80}" \
        --rows "${LINES:-24}" \
        --rendered-buffer "$_WISP_RENDERED_BUFFER" \
        --rendered-cursor "$_WISP_RENDERED_CURSOR" \
        --rendered-prompt "$_WISP_RENDERED_PROMPT" \
        --rendered-columns "$_WISP_RENDERED_COLUMNS" \
        --viewport-x "$_WISP_VIEWPORT_X" \
        --viewport-y "$_WISP_VIEWPORT_Y" \
        --grid-columns "$_WISP_GRID_COLUMNS" \
        --grid-rows "$_WISP_GRID_ROWS" \
        --shell bash \
        --no-wait \
        >/dev/null 2>&1
      _WISP_RENDERED_BUFFER=$buffer
      _WISP_RENDERED_CURSOR=$point
      _WISP_RENDERED_PROMPT=$_WISP_PROMPT
      _WISP_RENDERED_COLUMNS=${COLUMNS:-80}
    }

    _wisp_bash_insert_code() {
      local code=$1 character prefix suffix
      local LC_ALL=C
      printf -v character "\\$(printf '%03o' "$code")"
      prefix=${READLINE_LINE:0:READLINE_POINT}
      suffix=${READLINE_LINE:READLINE_POINT}
      READLINE_LINE="${prefix}${character}${suffix}"
      ((READLINE_POINT += 1))
      _WISP_HISTORY_OFFSET=0
      _wisp_bash_update
    }

    _wisp_bash_previous_boundary() {
      local text=$1 point=$2 byte
      local LC_ALL=C
      _WISP_BOUNDARY=$((point > 0 ? point - 1 : 0))
      while (( _WISP_BOUNDARY > 0 )); do
        printf -v byte '%d' "'${text:_WISP_BOUNDARY:1}"
        (( (byte & 0xC0) != 0x80 )) && break
        ((_WISP_BOUNDARY -= 1))
      done
    }

    _wisp_bash_next_boundary() {
      local text=$1 point=$2 length byte
      local LC_ALL=C
      length=${#text}
      _WISP_BOUNDARY=$((point < length ? point + 1 : length))
      while (( _WISP_BOUNDARY < length )); do
        printf -v byte '%d' "'${text:_WISP_BOUNDARY:1}"
        (( (byte & 0xC0) != 0x80 )) && break
        ((_WISP_BOUNDARY += 1))
      done
    }

    _wisp_bash_backspace() {
      local prefix suffix
      (( READLINE_POINT > 0 )) || return 0
      _wisp_bash_previous_boundary "$READLINE_LINE" "$READLINE_POINT"
      local LC_ALL=C
      prefix=${READLINE_LINE:0:_WISP_BOUNDARY}
      suffix=${READLINE_LINE:READLINE_POINT}
      READLINE_LINE=${prefix}${suffix}
      READLINE_POINT=$_WISP_BOUNDARY
      _WISP_HISTORY_OFFSET=0
      _wisp_bash_update
    }

    _wisp_bash_delete() {
      local prefix suffix
      local LC_ALL=C
      (( READLINE_POINT < ${#READLINE_LINE} )) || return 0
      _wisp_bash_next_boundary "$READLINE_LINE" "$READLINE_POINT"
      prefix=${READLINE_LINE:0:READLINE_POINT}
      suffix=${READLINE_LINE:_WISP_BOUNDARY}
      READLINE_LINE=${prefix}${suffix}
      _WISP_HISTORY_OFFSET=0
      _wisp_bash_update
    }

    _wisp_bash_left() {
      _wisp_bash_previous_boundary "$READLINE_LINE" "$READLINE_POINT"
      READLINE_POINT=$_WISP_BOUNDARY
      _wisp_bash_update
    }

    _wisp_bash_right() {
      local edit
      if edit=$(command "${WISP_BIN:-wisp}" shell accept --session "$WISP_SESSION_ID" --ghost --format bash 2>/dev/null); then
        eval "$edit"
        READLINE_LINE=$_WISP_EDIT_BUFFER
        _wisp_bash_char_to_byte "$READLINE_LINE" "$_WISP_EDIT_CURSOR"
        READLINE_POINT=$_WISP_BYTE_LENGTH
        _WISP_LAST_STATE=''
        _wisp_bash_update
      else
        _wisp_bash_next_boundary "$READLINE_LINE" "$READLINE_POINT"
        READLINE_POINT=$_WISP_BOUNDARY
        _wisp_bash_update
      fi
    }

    _wisp_bash_accept() {
      local edit
      if edit=$(command "${WISP_BIN:-wisp}" shell accept --session "$WISP_SESSION_ID" --format bash 2>/dev/null); then
        eval "$edit"
        READLINE_LINE=$_WISP_EDIT_BUFFER
        _wisp_bash_char_to_byte "$READLINE_LINE" "$_WISP_EDIT_CURSOR"
        READLINE_POINT=$_WISP_BYTE_LENGTH
        _WISP_LAST_STATE=''
        if (( _WISP_EDIT_CONTINUE )); then
          _wisp_bash_update
        else
          _WISP_RENDERED_BUFFER=$READLINE_LINE
          _WISP_RENDERED_CURSOR=$READLINE_POINT
          _WISP_RENDERED_PROMPT=$_WISP_PROMPT
        fi
      fi
    }

    _wisp_bash_history_previous() {
      if command "${WISP_BIN:-wisp}" shell navigate --session "$WISP_SESSION_ID" previous >/dev/null 2>&1; then
        return 0
      fi
      ((_WISP_HISTORY_OFFSET += 1))
      local entry
      entry=$(builtin fc -ln "-${_WISP_HISTORY_OFFSET}" "-${_WISP_HISTORY_OFFSET}" 2>/dev/null) || {
        ((_WISP_HISTORY_OFFSET -= 1))
        return 0
      }
      READLINE_LINE=$entry
      _wisp_bash_byte_length "$READLINE_LINE"
      READLINE_POINT=$_WISP_BYTE_LENGTH
      _WISP_LAST_STATE=''
    }

    _wisp_bash_history_next() {
      if command "${WISP_BIN:-wisp}" shell navigate --session "$WISP_SESSION_ID" next >/dev/null 2>&1; then
        return 0
      fi
      if (( _WISP_HISTORY_OFFSET <= 1 )); then
        _WISP_HISTORY_OFFSET=0
        READLINE_LINE=''
        READLINE_POINT=0
      else
        ((_WISP_HISTORY_OFFSET -= 1))
        READLINE_LINE=$(builtin fc -ln "-${_WISP_HISTORY_OFFSET}" "-${_WISP_HISTORY_OFFSET}" 2>/dev/null)
        _wisp_bash_byte_length "$READLINE_LINE"
        READLINE_POINT=$_WISP_BYTE_LENGTH
      fi
      _WISP_LAST_STATE=''
    }

    _wisp_bash_prompt_hook() {
      _wisp_bash_dismiss
      if (( BASH_VERSINFO[0] > 4 || BASH_VERSINFO[1] >= 4 )); then
        _WISP_PROMPT=${PS1@P}
      else
        _WISP_PROMPT=$PS1
      fi
      _WISP_LAST_STATE=''
      _WISP_RENDERED_BUFFER=''
      _WISP_RENDERED_CURSOR=0
      _WISP_RENDERED_PROMPT=$_WISP_PROMPT
      _WISP_HISTORY_OFFSET=0
    }

    _wisp_bash_install_bindings() {
      local code key
      for ((code = 32; code <= 126; code++)); do
        printf -v key '\\x%02x' "$code"
        bind -m emacs-standard -x "\"${key}\":_wisp_bash_insert_code ${code}"
        bind -m vi-insert -x "\"${key}\":_wisp_bash_insert_code ${code}" 2>/dev/null || true
      done
      for keymap in emacs-standard vi-insert; do
        bind -m "$keymap" -x '"\C-?":_wisp_bash_backspace' 2>/dev/null || true
        bind -m "$keymap" -x '"\C-h":_wisp_bash_backspace' 2>/dev/null || true
        bind -m "$keymap" -x '"\e[3~":_wisp_bash_delete' 2>/dev/null || true
        bind -m "$keymap" -x '"\e[D":_wisp_bash_left' 2>/dev/null || true
        bind -m "$keymap" -x '"\eOD":_wisp_bash_left' 2>/dev/null || true
        bind -m "$keymap" -x '"\e[C":_wisp_bash_right' 2>/dev/null || true
        bind -m "$keymap" -x '"\eOC":_wisp_bash_right' 2>/dev/null || true
        bind -m "$keymap" -x '"\e[A":_wisp_bash_history_previous' 2>/dev/null || true
        bind -m "$keymap" -x '"\eOA":_wisp_bash_history_previous' 2>/dev/null || true
        bind -m "$keymap" -x '"\e[B":_wisp_bash_history_next' 2>/dev/null || true
        bind -m "$keymap" -x '"\eOB":_wisp_bash_history_next' 2>/dev/null || true
        bind -m "$keymap" -x '"\C-p":_wisp_bash_history_previous' 2>/dev/null || true
        bind -m "$keymap" -x '"\C-n":_wisp_bash_history_next' 2>/dev/null || true
        bind -m "$keymap" -x '"\C-i":_wisp_bash_accept' 2>/dev/null || true
        bind -m "$keymap" -x '"\C-g":_wisp_bash_dismiss' 2>/dev/null || true
      done
    }

    _wisp_bash_refresh_viewport
    _wisp_bash_install_bindings
    if [[ ${PROMPT_COMMAND:-} != *'_wisp_bash_prompt_hook'* ]]; then
      PROMPT_COMMAND="_wisp_bash_prompt_hook${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
    fi
  fi
fi
