# Wisp Fish integration. Generated by wisp init fish.

if status is-interactive; and not set -q _WISP_FISH_LOADED
    set -g _WISP_FISH_LOADED 1
    set -gx WISP_SESSION_ID "fish-$fish_pid-"(random)
    set -g _WISP_REQUEST_ID 0
    set -g _WISP_LAST_STATE ''
    set -g _WISP_RENDERED_BUFFER ''
    set -g _WISP_RENDERED_CURSOR 0
    set -g _WISP_RENDERED_COLUMNS $COLUMNS
    set -g _WISP_VIEWPORT_X 0
    set -g _WISP_VIEWPORT_Y 0
    set -g _WISP_PANE_COLUMNS $COLUMNS
    set -g _WISP_PANE_ROWS $LINES
    set -g _WISP_GRID_COLUMNS $COLUMNS
    set -g _WISP_GRID_ROWS $LINES

    function _wisp_fish_refresh_viewport
        if set -q ZELLIJ
            command "$WISP_BIN" shell viewport --format fish 2>/dev/null | source
            or return
        else
            set -g _WISP_VIEWPORT_X 0
            set -g _WISP_VIEWPORT_Y 0
            set -g _WISP_PANE_COLUMNS $COLUMNS
            set -g _WISP_PANE_ROWS $LINES
            set -g _WISP_GRID_COLUMNS $COLUMNS
            set -g _WISP_GRID_ROWS $LINES
        end
    end

    function _wisp_fish_dismiss
        command "$WISP_BIN" shell dismiss \
            --session "$WISP_SESSION_ID" \
            --request-id "$_WISP_REQUEST_ID" \
            >/dev/null 2>&1
    end

    function _wisp_fish_update
        commandline --search-mode; and return
        commandline --paging-mode; and return
        if test $_WISP_PANE_COLUMNS -ne $COLUMNS -o $_WISP_PANE_ROWS -ne $LINES
            _wisp_fish_refresh_viewport
        end
        set -l buffer (commandline)
        set -l cursor (commandline --cursor)
        set -l state "$_WISP_VIEWPORT_X:$_WISP_VIEWPORT_Y:$COLUMNS:$LINES:$cursor:$buffer"
        test "$state" = "$_WISP_LAST_STATE"; and return
        set -g _WISP_LAST_STATE "$state"
        set -g _WISP_REQUEST_ID (math $_WISP_REQUEST_ID + 1)
        command "$WISP_BIN" shell update \
            --session "$WISP_SESSION_ID" \
            --request-id "$_WISP_REQUEST_ID" \
            --buffer "$buffer" \
            --cursor "$cursor" \
            --cwd "$PWD" \
            --columns "$COLUMNS" \
            --rows "$LINES" \
            --rendered-buffer "$_WISP_RENDERED_BUFFER" \
            --rendered-cursor "$_WISP_RENDERED_CURSOR" \
            --rendered-columns "$_WISP_RENDERED_COLUMNS" \
            --viewport-x "$_WISP_VIEWPORT_X" \
            --viewport-y "$_WISP_VIEWPORT_Y" \
            --grid-columns "$_WISP_GRID_COLUMNS" \
            --grid-rows "$_WISP_GRID_ROWS" \
            --shell fish \
            --no-wait \
            >/dev/null 2>&1
        set -g _WISP_RENDERED_BUFFER "$buffer"
        set -g _WISP_RENDERED_CURSOR "$cursor"
        set -g _WISP_RENDERED_COLUMNS "$COLUMNS"
    end

    function _wisp_fish_accept
        set -l edit_output (command "$WISP_BIN" shell accept --session "$WISP_SESSION_ID" --format fish 2>/dev/null)
        set -l edit_status $status
        if test $edit_status -eq 0
            printf '%s\n' $edit_output | source
            commandline --replace -- "$_WISP_EDIT_BUFFER"
            commandline --cursor "$_WISP_EDIT_CURSOR"
            set -g _WISP_LAST_STATE ''
            if test "$_WISP_EDIT_CONTINUE" -eq 1
                _wisp_fish_update
            else
                set -g _WISP_RENDERED_BUFFER "$_WISP_EDIT_BUFFER"
                set -g _WISP_RENDERED_CURSOR "$_WISP_EDIT_CURSOR"
            end
            commandline --function repaint
        else
            commandline --function complete
        end
    end

    function _wisp_fish_accept_ghost
        set -l edit_output (command "$WISP_BIN" shell accept --session "$WISP_SESSION_ID" --ghost --format fish 2>/dev/null)
        set -l edit_status $status
        if test $edit_status -eq 0
            printf '%s\n' $edit_output | source
            commandline --replace -- "$_WISP_EDIT_BUFFER"
            commandline --cursor "$_WISP_EDIT_CURSOR"
            set -g _WISP_LAST_STATE ''
            _wisp_fish_update
            commandline --function repaint
        else
            commandline --function forward-char-passive
            _wisp_fish_update
        end
    end

    function _wisp_fish_previous
        if command "$WISP_BIN" shell navigate --session "$WISP_SESSION_ID" previous >/dev/null 2>&1
            commandline --function repaint
        else
            commandline --function up-or-search
            set -g _WISP_LAST_STATE ''
        end
    end

    function _wisp_fish_next
        if command "$WISP_BIN" shell navigate --session "$WISP_SESSION_ID" next >/dev/null 2>&1
            commandline --function repaint
        else
            commandline --function down-or-search
            set -g _WISP_LAST_STATE ''
        end
    end

    function _wisp_fish_escape
        if _wisp_fish_dismiss
            commandline --function repaint
        else
            commandline --function cancel
        end
    end

    function _wisp_fish_after_edit
        _wisp_fish_update
    end

    function _wisp_fish_install_bindings
        set -l modes default
        if test "$fish_key_bindings" = fish_vi_key_bindings
            set modes insert
        end
        for mode in $modes
            bind --mode "$mode" '' self-insert _wisp_fish_after_edit
            bind --mode "$mode" space self-insert _wisp_fish_after_edit
            bind --mode "$mode" backspace backward-delete-char _wisp_fish_after_edit
            bind --mode "$mode" delete delete-char _wisp_fish_after_edit
            bind --mode "$mode" left backward-char _wisp_fish_after_edit
            bind --mode "$mode" right _wisp_fish_accept_ghost
            bind --mode "$mode" up _wisp_fish_previous
            bind --mode "$mode" down _wisp_fish_next
            bind --mode "$mode" ctrl-p _wisp_fish_previous
            bind --mode "$mode" ctrl-n _wisp_fish_next
            bind --mode "$mode" tab _wisp_fish_accept
            bind --mode "$mode" ctrl-g _wisp_fish_escape
            bind --mode "$mode" escape _wisp_fish_escape
        end
    end

    function _wisp_fish_prompt --on-event fish_prompt
        set -l previous_status $status
        _wisp_fish_dismiss >/dev/null 2>&1
        set -g _WISP_LAST_STATE ''
        set -g _WISP_RENDERED_BUFFER ''
        set -g _WISP_RENDERED_CURSOR 0
        _wisp_fish_install_bindings
        return $previous_status
    end

    function _wisp_fish_cancel --on-event fish_cancel
        _wisp_fish_dismiss >/dev/null 2>&1
    end

    function _wisp_fish_focus_out --on-event fish_focus_out
        _wisp_fish_dismiss >/dev/null 2>&1
    end

    _wisp_fish_refresh_viewport
    _wisp_fish_install_bindings
end
