# Wisp Zsh integration. Generated by wisp init zsh.
autoload -Uz add-zle-hook-widget
zmodload zsh/terminfo 2>/dev/null
zmodload zsh/system 2>/dev/null
zmodload zsh/zselect 2>/dev/null

if [[ -z "${_WISP_SEQUENCE_PROTOCOL:-}" ]]; then
  # Use a fresh session when upgrading from the timestamp-based request protocol.
  # The random suffix also prevents nested interactive shells sharing a session.
  export WISP_SESSION_ID="zsh-${ZSH_PID:-$$}-${RANDOM}${RANDOM}"
  typeset -g _WISP_SEQUENCE_PROTOCOL=1
fi
typeset -g _WISP_LAST_STATE=""
typeset -gi _WISP_REQUEST_ID="${_WISP_REQUEST_ID:-0}"
typeset -gi _WISP_TTY_FD=-1
typeset -g _WISP_CURSOR_OUTPUT=""
typeset -gi _WISP_SUPPRESS_REDRAW=0
typeset -g _WISP_RENDERED_BUFFER=""
typeset -gi _WISP_RENDERED_CURSOR=0
typeset -g _WISP_RENDERED_PROMPT="${(%)PROMPT}"
typeset -gi _WISP_RENDERED_COLUMNS="${COLUMNS:-80}"
typeset -gi _WISP_VIEWPORT_X=0
typeset -gi _WISP_VIEWPORT_Y=0
typeset -gi _WISP_PANE_COLUMNS="${COLUMNS:-80}"
typeset -gi _WISP_PANE_ROWS="${LINES:-24}"
typeset -gi _WISP_GRID_COLUMNS="${COLUMNS:-80}"
typeset -gi _WISP_GRID_ROWS="${LINES:-24}"

if zmodload -e zsh/system && zmodload -e zsh/zselect; then
  sysopen -rw -u _WISP_TTY_FD /dev/tty 2>/dev/null || _WISP_TTY_FD=-1
fi

function _wisp_refresh_terminal_viewport() {
  local geometry=''
  if [[ -n "${ZELLIJ:-}" ]] && \
     geometry="$(command "${WISP_BIN:-wisp}" shell viewport 2>/dev/null)"; then
    eval "$geometry"
  else
    _WISP_VIEWPORT_X=0
    _WISP_VIEWPORT_Y=0
    _WISP_PANE_COLUMNS="${COLUMNS:-80}"
    _WISP_PANE_ROWS="${LINES:-24}"
    _WISP_GRID_COLUMNS="${COLUMNS:-80}"
    _WISP_GRID_ROWS="${LINES:-24}"
  fi
}

function _wisp_cursor_position() {
  local byte='' report='' pending='' position='' row='' column=''
  local -i state=0 bytes_read=0 found=0 wait_ticks=2
  _WISP_CURSOR_OUTPUT=''
  (( _WISP_TTY_FD >= 0 )) || return 1
  # Supported terminals implement the standard CSI 6n cursor-position report. ZLE is
  # paused while this hook runs. Read the complete response byte by byte:
  # a single sysread can legally return only ESC and leave "[row;columnR" for
  # ZLE, which would then insert the control sequence into the command line.
  print -nu "$_WISP_TTY_FD" -- $'\e[6n'
  while (( bytes_read < 64 )); do
    # Once an ESC/CSI prefix has arrived, allow extra time for the rest of the
    # same report so a delayed tail can never escape into ZLE.
    (( state > 0 )) && wait_ticks=10 || wait_ticks=2
    zselect -r "$_WISP_TTY_FD" -t "$wait_ticks" >/dev/null 2>&1 || break
    byte=''
    sysread -i "$_WISP_TTY_FD" -s 1 byte 2>/dev/null || break
    (( bytes_read += 1 ))
    case "$state" in
      0)
        if [[ "$byte" == $'\e' ]]; then
          report="$byte"
          state=1
        else
          pending+="$byte"
        fi
        ;;
      1)
        if [[ "$byte" == '[' ]]; then
          report+="$byte"
          state=2
        else
          pending+="$report$byte"
          report=''
          state=0
        fi
        ;;
      2)
        report+="$byte"
        if [[ "$byte" == 'R' ]]; then
          position="${report#$'\e['}"
          position="${position%R}"
          row="${position%%;*}"
          column="${position#*;}"
          if [[ "$row" == <-> && "$column" == <-> ]]; then
            found=1
            break
          fi
          pending+="$report"
          report=''
          state=0
        elif [[ "$byte" != [0-9] && "$byte" != ';' ]]; then
          # This was another escape sequence (for example an arrow key), not
          # a cursor report. Preserve it and continue waiting for the DSR.
          pending+="$report"
          report=''
          state=0
        fi
        ;;
    esac
  done

  # Fast typing can queue a real key before the terminal response. Put those
  # bytes back so querying the cursor never eats user input. An incomplete
  # DSR prefix in `report` is deliberately discarded instead of leaking into
  # BUFFER as visible "[row;column" text.
  [[ -n "$pending" ]] && zle -U "$pending"
  (( found )) || return 1
  row="${position%%;*}"
  column="${position#*;}"
  # The report describes the frame currently painted by ZLE. Wisp combines
  # both coordinates with the old-to-new buffer layout delta.
  _WISP_CURSOR_OUTPUT="--cursor-row $row --cursor-column $column"
}

function _wisp_line_pre_redraw() {
  local current_prompt="${(%)PROMPT}"
  if (( _WISP_PANE_COLUMNS != ${COLUMNS:-80} || _WISP_PANE_ROWS != ${LINES:-24} )); then
    _wisp_refresh_terminal_viewport
  fi
  local state="${_WISP_VIEWPORT_X}:${_WISP_VIEWPORT_Y}:${COLUMNS:-80}:${LINES:-24}:${CURSOR}:${BUFFER}"
  local cursor_output=''
  local -a cursor_position
  [[ "$state" == "$_WISP_LAST_STATE" ]] && return
  _WISP_LAST_STATE="$state"
  (( _WISP_REQUEST_ID += 1 ))
  if (( _WISP_SUPPRESS_REDRAW )); then
    _WISP_SUPPRESS_REDRAW=0
    command "${WISP_BIN:-wisp}" shell dismiss \
      --session "$WISP_SESSION_ID" \
      --request-id "$(( _WISP_REQUEST_ID - 1 ))" \
      >/dev/null 2>&1 &!
    _WISP_RENDERED_BUFFER="$BUFFER"
    _WISP_RENDERED_CURSOR="$CURSOR"
    _WISP_RENDERED_PROMPT="$current_prompt"
    _WISP_RENDERED_COLUMNS="${COLUMNS:-80}"
    return
  fi
  _wisp_cursor_position || _WISP_CURSOR_OUTPUT=''
  cursor_output="$_WISP_CURSOR_OUTPUT"
  cursor_position=(${=cursor_output})

  command "${WISP_BIN:-wisp}" shell update \
    --session "$WISP_SESSION_ID" \
    --request-id "$_WISP_REQUEST_ID" \
    --buffer "$BUFFER" \
    --cursor "$CURSOR" \
    --cwd "$PWD" \
    --prompt "${(%)PROMPT}" \
    --columns "${COLUMNS:-80}" \
    --rows "${LINES:-24}" \
    "${cursor_position[@]}" \
    --rendered-buffer "$_WISP_RENDERED_BUFFER" \
    --rendered-cursor "$_WISP_RENDERED_CURSOR" \
    --rendered-prompt "$_WISP_RENDERED_PROMPT" \
    --rendered-columns "$_WISP_RENDERED_COLUMNS" \
    --viewport-x "$_WISP_VIEWPORT_X" \
    --viewport-y "$_WISP_VIEWPORT_Y" \
    --grid-columns "$_WISP_GRID_COLUMNS" \
    --grid-rows "$_WISP_GRID_ROWS" \
    --window-id "${ALACRITTY_WINDOW_ID:-}" \
    >/dev/null 2>&1 &!

  _WISP_RENDERED_BUFFER="$BUFFER"
  _WISP_RENDERED_CURSOR="$CURSOR"
  _WISP_RENDERED_PROMPT="$current_prompt"
  _WISP_RENDERED_COLUMNS="${COLUMNS:-80}"
}

function _wisp_accept() {
  local edit
  if edit="$(command "${WISP_BIN:-wisp}" shell accept --session "$WISP_SESSION_ID" 2>/dev/null)"; then
    eval "$edit"
    if (( ${WISP_CONTINUE:-0} )); then
      _WISP_LAST_STATE=""
      _wisp_line_pre_redraw
    else
      _WISP_LAST_STATE="${_WISP_VIEWPORT_X}:${_WISP_VIEWPORT_Y}:${COLUMNS:-80}:${LINES:-24}:${CURSOR}:${BUFFER}"
      _WISP_RENDERED_BUFFER="$BUFFER"
      _WISP_RENDERED_CURSOR="$CURSOR"
      _WISP_RENDERED_PROMPT="${(%)PROMPT}"
      _WISP_RENDERED_COLUMNS="${COLUMNS:-80}"
    fi
    zle redisplay
  else
    zle expand-or-complete
  fi
}

function _wisp_accept_ghost() {
  local edit
  if edit="$(command "${WISP_BIN:-wisp}" shell accept --session "$WISP_SESSION_ID" --ghost 2>/dev/null)"; then
    eval "$edit"
    _WISP_LAST_STATE=""
    zle redisplay
  else
    zle forward-char
  fi
}

function _wisp_next() {
  if command "${WISP_BIN:-wisp}" shell navigate --session "$WISP_SESSION_ID" next >/dev/null 2>&1; then
    zle redisplay
  else
    zle down-line-or-history
    _WISP_SUPPRESS_REDRAW=1
  fi
}

function _wisp_previous() {
  if command "${WISP_BIN:-wisp}" shell navigate --session "$WISP_SESSION_ID" previous >/dev/null 2>&1; then
    zle redisplay
  else
    zle up-line-or-history
    _WISP_SUPPRESS_REDRAW=1
  fi
}

function _wisp_try_dismiss() {
  command "${WISP_BIN:-wisp}" shell dismiss \
    --session "$WISP_SESSION_ID" \
    --request-id "$_WISP_REQUEST_ID" \
    >/dev/null 2>&1
}

function _wisp_dismiss() {
  _wisp_try_dismiss
  zle redisplay
}

function _wisp_escape() {
  if _wisp_try_dismiss; then
    zle redisplay
  elif [[ "${KEYMAP:-}" == viins ]]; then
    zle vi-cmd-mode
  fi
}

function _wisp_line_finish() {
  _WISP_LAST_STATE=""
  command "${WISP_BIN:-wisp}" shell dismiss \
    --session "$WISP_SESSION_ID" \
    --request-id "$_WISP_REQUEST_ID" \
    >/dev/null 2>&1 &!
}

zle -N _wisp_accept
zle -N _wisp_accept_ghost
zle -N _wisp_next
zle -N _wisp_previous
zle -N _wisp_dismiss
zle -N _wisp_escape
add-zle-hook-widget line-pre-redraw _wisp_line_pre_redraw
add-zle-hook-widget line-finish _wisp_line_finish

function _wisp_bind_key() {
  local sequence="$1"
  local widget="$2"
  local keymap
  [[ -z "$sequence" ]] && return
  for keymap in main emacs viins vicmd; do
    bindkey -M "$keymap" "$sequence" "$widget" 2>/dev/null
  done
}

function _wisp_install_bindings() {
  _wisp_bind_key $'\t' _wisp_accept
  _wisp_bind_key $'\C-G' _wisp_dismiss
  _wisp_bind_key $'\e' _wisp_escape

  # Ctrl-P/N are terminal-independent alternatives to Up/Down. Their fallback
  # remains normal shell history when Wisp has no active candidates.
  _wisp_bind_key $'\C-P' _wisp_previous
  _wisp_bind_key $'\C-N' _wisp_next

  # Depending on ZLE's cursor-key mode, Alacritty sends either CSI (Esc [)
  # or SS3 (Esc O) sequences. Bind terminfo plus both standard encodings.
  _wisp_bind_key "${terminfo[kcuu1]:-}" _wisp_previous
  _wisp_bind_key "${terminfo[kcud1]:-}" _wisp_next
  _wisp_bind_key "${terminfo[kcuf1]:-}" _wisp_accept_ghost
  _wisp_bind_key $'\e[A' _wisp_previous
  _wisp_bind_key $'\eOA' _wisp_previous
  _wisp_bind_key $'\e[B' _wisp_next
  _wisp_bind_key $'\eOB' _wisp_next
  _wisp_bind_key $'\e[C' _wisp_accept_ghost
  _wisp_bind_key $'\eOC' _wisp_accept_ghost
}

function _wisp_line_init() {
  _WISP_LAST_STATE=""
  _WISP_RENDERED_BUFFER="$BUFFER"
  _WISP_RENDERED_CURSOR="$CURSOR"
  _WISP_RENDERED_PROMPT="${(%)PROMPT}"
  _WISP_RENDERED_COLUMNS="${COLUMNS:-80}"
  command "${WISP_BIN:-wisp}" shell dismiss \
    --session "$WISP_SESSION_ID" \
    --request-id "$_WISP_REQUEST_ID" \
    >/dev/null 2>&1 &!
  _wisp_install_bindings
}

function _wisp_keymap_select() {
  _wisp_install_bindings
}

zle -N _wisp_line_init
zle -N _wisp_keymap_select
add-zle-hook-widget line-init _wisp_line_init
add-zle-hook-widget keymap-select _wisp_keymap_select
_wisp_refresh_terminal_viewport
_wisp_install_bindings
