# Wisp Nushell integration. Generated by wisp init nushell.

if not ($env | columns | any {|name| $name == '_WISP_NUSHELL_LOADED' }) {
    $env._WISP_NUSHELL_LOADED = true
    $env.WISP_SESSION_ID = $"nu-($nu.pid)-(random int 100000..999999)"
    $env._WISP_REQUEST_ID = 0
    $env._WISP_LAST_STATE = ''
    $env._WISP_RENDERED_BUFFER = ''
    $env._WISP_RENDERED_CURSOR = 0
    $env._WISP_RENDERED_COLUMNS = 80
    $env._WISP_HISTORY_OFFSET = 0
    $env._WISP_VIEWPORT_X = 0
    $env._WISP_VIEWPORT_Y = 0
    $env._WISP_PANE_COLUMNS = 80
    $env._WISP_PANE_ROWS = 24
    $env._WISP_GRID_COLUMNS = 80
    $env._WISP_GRID_ROWS = 24

    def --env _wisp_nu_refresh_viewport [] {
        let size = term size
        if ($env | columns | any {|name| $name == 'ZELLIJ' }) {
            let args = [shell viewport '--format' json]
            let result = (do { run-external $env.WISP_BIN ...$args } | complete)
            if $result.exit_code == 0 {
                let geometry = ($result.stdout | from json)
                $env._WISP_VIEWPORT_X = $geometry.viewport_x
                $env._WISP_VIEWPORT_Y = $geometry.viewport_y
                $env._WISP_PANE_COLUMNS = $geometry.pane_columns
                $env._WISP_PANE_ROWS = $geometry.pane_rows
                $env._WISP_GRID_COLUMNS = $geometry.grid_columns
                $env._WISP_GRID_ROWS = $geometry.grid_rows
                return
            }
        }
        $env._WISP_VIEWPORT_X = 0
        $env._WISP_VIEWPORT_Y = 0
        $env._WISP_PANE_COLUMNS = $size.columns
        $env._WISP_PANE_ROWS = $size.rows
        $env._WISP_GRID_COLUMNS = $size.columns
        $env._WISP_GRID_ROWS = $size.rows
    }

    def _wisp_nu_dismiss [] {
        let args = [shell dismiss '--session' $env.WISP_SESSION_ID '--request-id' $env._WISP_REQUEST_ID]
        do {
            run-external $env.WISP_BIN ...$args
        } | complete | ignore
    }

    def --env _wisp_nu_update [] {
        let buffer = commandline
        let cursor = commandline get-cursor
        let size = term size
        if ($env | columns | any {|name| $name == 'ZELLIJ' }) and (
            $env._WISP_PANE_COLUMNS != $size.columns or $env._WISP_PANE_ROWS != $size.rows
        ) {
            _wisp_nu_refresh_viewport
        }
        let state = $"($env._WISP_VIEWPORT_X):($env._WISP_VIEWPORT_Y):($size.columns):($size.rows):($cursor):($buffer)"
        if $state == $env._WISP_LAST_STATE {
            return
        }
        $env._WISP_LAST_STATE = $state
        $env._WISP_REQUEST_ID += 1

        let report = try {
            term query (ansi cursor_position) --prefix (ansi csi) --terminator 'R'
            | decode utf-8
        } catch { '' }
        let coordinates = ($report | split row ';')
        let cursor_args = if ($coordinates | length) == 2 {
            try {
                ['--cursor-row' ($coordinates.0 | into int) '--cursor-column' ($coordinates.1 | into int)]
            } catch { [] }
        } else { [] }
        let args = [
            shell update
            '--session' $env.WISP_SESSION_ID
            '--request-id' $env._WISP_REQUEST_ID
            '--buffer' $buffer
            '--cursor' $cursor
            '--cursor-unit' bytes
            '--cwd' ($env.PWD | into string)
            '--columns' $size.columns
            '--rows' $size.rows
            '--rendered-buffer' $env._WISP_RENDERED_BUFFER
            '--rendered-cursor' $env._WISP_RENDERED_CURSOR
            '--rendered-columns' $env._WISP_RENDERED_COLUMNS
            '--viewport-x' $env._WISP_VIEWPORT_X
            '--viewport-y' $env._WISP_VIEWPORT_Y
            '--grid-columns' $env._WISP_GRID_COLUMNS
            '--grid-rows' $env._WISP_GRID_ROWS
            '--shell' nushell
            '--no-wait'
        ] | append $cursor_args
        do { run-external $env.WISP_BIN ...$args } | complete | ignore
        $env._WISP_RENDERED_BUFFER = $buffer
        $env._WISP_RENDERED_CURSOR = $cursor
        $env._WISP_RENDERED_COLUMNS = $size.columns
        $env._WISP_HISTORY_OFFSET = 0
    }

    def --env _wisp_nu_apply_edit [ghost: bool] {
        let ghost_args = if $ghost { ['--ghost'] } else { [] }
        let args = [shell accept '--session' $env.WISP_SESSION_ID '--format' json] | append $ghost_args
        let result = (do {
            run-external $env.WISP_BIN ...$args
        } | complete)
        if $result.exit_code != 0 {
            return false
        }
        let edit = ($result.stdout | from json)
        commandline edit --replace $edit.buffer
        let prefix = ($edit.buffer | str substring ..<$edit.cursor)
        let byte_cursor = ($prefix | encode utf-8 | bytes length)
        commandline set-cursor $byte_cursor
        $env._WISP_LAST_STATE = ''
        if $edit.continue_completion or $ghost {
            _wisp_nu_update
        } else {
            $env._WISP_RENDERED_BUFFER = $edit.buffer
            $env._WISP_RENDERED_CURSOR = $byte_cursor
        }
        true
    }

    def --env _wisp_nu_accept [] {
        _wisp_nu_apply_edit false | ignore
    }

    def --env _wisp_nu_right [] {
        if not (_wisp_nu_apply_edit true) {
            commandline set-cursor ((commandline get-cursor) + 1)
            _wisp_nu_update
        }
    }

    def --env _wisp_nu_previous [] {
        let args = [shell navigate '--session' $env.WISP_SESSION_ID previous]
        let result = (do {
            run-external $env.WISP_BIN ...$args
        } | complete)
        if $result.exit_code == 0 {
            return
        }
        $env._WISP_HISTORY_OFFSET += 1
        let entries = (history | reverse)
        let index = $env._WISP_HISTORY_OFFSET - 1
        if $index < ($entries | length) {
            let entry = ($entries | get $index)
            let line = ($entry | get -o command | default ($entry | get -o command_line | default ''))
            commandline edit --replace $line
            commandline set-cursor --end
            $env._WISP_LAST_STATE = ''
        } else {
            $env._WISP_HISTORY_OFFSET -= 1
        }
    }

    def --env _wisp_nu_next [] {
        let args = [shell navigate '--session' $env.WISP_SESSION_ID next]
        let result = (do {
            run-external $env.WISP_BIN ...$args
        } | complete)
        if $result.exit_code == 0 {
            return
        }
        if $env._WISP_HISTORY_OFFSET <= 1 {
            $env._WISP_HISTORY_OFFSET = 0
            commandline edit --replace ''
            commandline set-cursor 0
        } else {
            $env._WISP_HISTORY_OFFSET -= 1
            let entry = (history | reverse | get ($env._WISP_HISTORY_OFFSET - 1))
            let line = ($entry | get -o command | default ($entry | get -o command_line | default ''))
            commandline edit --replace $line
            commandline set-cursor --end
        }
        $env._WISP_LAST_STATE = ''
    }

    def --env _wisp_nu_prompt_hook [] {
        _wisp_nu_dismiss
        $env._WISP_LAST_STATE = ''
        $env._WISP_RENDERED_BUFFER = ''
        $env._WISP_RENDERED_CURSOR = 0
        $env._WISP_HISTORY_OFFSET = 0
    }

    let update_command = '_wisp_nu_update'
    let character_bindings = (
        (97..122 | append (48..57))
        | each {|code|
            let character = (char --integer $code)
            {
                name: $"wisp_insert_($code)"
                modifier: none
                keycode: $"char_($character)"
                mode: [emacs vi_insert]
                event: [
                    { edit: insertchar value: $character }
                    { send: executehostcommand cmd: $update_command }
                ]
            }
        }
    )
    let shifted_letters = (
        97..122
        | each {|code|
            let lower = (char --integer $code)
            let upper = ($lower | str uppercase)
            {
                name: $"wisp_insert_shift_($code)"
                modifier: shift
                keycode: $"char_($lower)"
                mode: [emacs vi_insert]
                event: [
                    { edit: insertchar value: $upper }
                    { send: executehostcommand cmd: $update_command }
                ]
            }
        }
    )
    let punctuation_bindings = (
        (33..47 | append (58..64) | append (91..96) | append (123..126))
        | enumerate
        | each {|item|
            let character = (char --integer $item.item)
            let code = ($item.item | format number --no-prefix | get lowerhex)
            {
                name: $"wisp_insert_punctuation_($item.index)"
                modifier: none
                keycode: $"char_u($code)"
                mode: [emacs vi_insert]
                event: [
                    { edit: insertchar value: $character }
                    { send: executehostcommand cmd: $update_command }
                ]
            }
        }
    )
    let control_bindings = [
        {
            name: wisp_insert_space
            modifier: none
            keycode: space
            mode: [emacs vi_insert]
            event: [{ edit: insertchar value: ' ' } { send: executehostcommand cmd: $update_command }]
        }
        {
            name: wisp_backspace
            modifier: none
            keycode: backspace
            mode: [emacs vi_insert]
            event: [{ edit: backspace } { send: executehostcommand cmd: $update_command }]
        }
        {
            name: wisp_delete
            modifier: none
            keycode: delete
            mode: [emacs vi_insert]
            event: [{ edit: delete } { send: executehostcommand cmd: $update_command }]
        }
        {
            name: wisp_left
            modifier: none
            keycode: left
            mode: [emacs vi_insert]
            event: [{ edit: moveleft } { send: executehostcommand cmd: $update_command }]
        }
        {
            name: wisp_right
            modifier: none
            keycode: right
            mode: [emacs vi_insert]
            event: { send: executehostcommand cmd: '_wisp_nu_right' }
        }
        {
            name: wisp_previous
            modifier: none
            keycode: up
            mode: [emacs vi_insert]
            event: { send: executehostcommand cmd: '_wisp_nu_previous' }
        }
        {
            name: wisp_next
            modifier: none
            keycode: down
            mode: [emacs vi_insert]
            event: { send: executehostcommand cmd: '_wisp_nu_next' }
        }
        {
            name: wisp_accept
            modifier: none
            keycode: tab
            mode: [emacs vi_insert]
            event: { send: executehostcommand cmd: '_wisp_nu_accept' }
        }
        {
            name: wisp_dismiss
            modifier: control
            keycode: char_g
            mode: [emacs vi_insert]
            event: { send: executehostcommand cmd: '_wisp_nu_dismiss' }
        }
    ]
    $env.config.keybindings ++= ($character_bindings ++ $shifted_letters ++ $punctuation_bindings ++ $control_bindings)
    $env.config.hooks.pre_prompt = ($env.config.hooks.pre_prompt | append {|| _wisp_nu_prompt_hook })
    $env.config.hooks.pre_execution = ($env.config.hooks.pre_execution | append {|| _wisp_nu_dismiss })
    _wisp_nu_refresh_viewport
}
