use std::{
    path::{Path, PathBuf},
    process::{Command, Stdio},
    time::{Duration, SystemTime, UNIX_EPOCH},
};

use anyhow::{Context, bail};
use clap::{Args, Parser, Subcommand, ValueEnum};
use directories::ProjectDirs;
use serde::Deserialize;
use tokio::net::UnixStream;
use wisp_config::WispConfig;
use wisp_platform::TerminalCursorLocator;
use wisp_protocol::{
    AcceptTarget, ApplyEdit, BufferSnapshot, ClientMessage, NavigationDirection,
    RenderedCursorSnapshot, ServerMessage, ShellKind, TerminalKind, TerminalSnapshot,
    TerminalViewport, framed, receive_message, send_message,
};

#[derive(Debug, Parser)]
#[command(version, about = "Fast terminal autocomplete")]
struct Cli {
    #[arg(long, global = true, env = "WISP_SOCKET")]
    socket: Option<PathBuf>,
    #[arg(long, global = true)]
    config: Option<PathBuf>,
    #[command(subcommand)]
    command: CommandKind,
}

#[derive(Debug, Subcommand)]
enum CommandKind {
    /// Start the daemon and GPUI overlay.
    Start,
    /// Print shell integration code.
    Init { shell: InitShell },
    /// Commands used by shell integration.
    Shell {
        #[command(subcommand)]
        command: Box<ShellCommand>,
    },
    /// Check daemon and terminal integration.
    Doctor,
    /// Send a sample completion request.
    Demo {
        #[arg(default_value = "git ch")]
        buffer: String,
    },
    /// Test the daemon connection.
    Ping,
}

#[derive(Debug, Clone, Copy, ValueEnum)]
enum InitShell {
    Zsh,
    Bash,
    Fish,
    Nushell,
}

#[derive(Debug, Subcommand)]
enum ShellCommand {
    Update(Box<UpdateArgs>),
    Navigate(SessionArgsWithDirection),
    Accept(AcceptArgs),
    Dismiss(DismissArgs),
    /// Print the active zellij pane geometry for a shell adapter.
    Viewport(ViewportArgs),
}

#[derive(Debug, Args)]
struct UpdateArgs {
    #[arg(long, env = "WISP_SESSION_ID")]
    session: String,
    /// Monotonic sequence generated by the shell integration.
    #[arg(long)]
    request_id: Option<u64>,
    #[arg(long)]
    buffer: String,
    #[arg(long)]
    cursor: usize,
    #[arg(long, value_enum, default_value_t = CursorUnit::Characters)]
    cursor_unit: CursorUnit,
    #[arg(long)]
    cwd: PathBuf,
    #[arg(long, default_value = "")]
    prompt: String,
    #[arg(long, default_value_t = 80)]
    columns: u16,
    #[arg(long, default_value_t = 24)]
    rows: u16,
    /// One-based terminal cursor row from a CSI 6n response.
    #[arg(long)]
    cursor_row: Option<u16>,
    /// One-based terminal cursor column from a CSI 6n response.
    #[arg(long)]
    cursor_column: Option<u16>,
    /// Buffer state painted when the terminal cursor position was sampled.
    #[arg(long)]
    rendered_buffer: Option<String>,
    #[arg(long)]
    rendered_cursor: Option<usize>,
    #[arg(long)]
    rendered_prompt: Option<String>,
    #[arg(long)]
    rendered_columns: Option<u16>,
    #[arg(long)]
    viewport_x: Option<u16>,
    #[arg(long)]
    viewport_y: Option<u16>,
    #[arg(long)]
    grid_columns: Option<u16>,
    #[arg(long)]
    grid_rows: Option<u16>,
    #[arg(long, value_enum, default_value_t = TerminalArg::Auto)]
    terminal: TerminalArg,
    #[arg(long)]
    window_id: Option<String>,
    #[arg(long, value_enum, default_value_t = ShellArg::Zsh)]
    shell: ShellArg,
    /// Send the snapshot and return without waiting for completion results.
    #[arg(long)]
    no_wait: bool,
}

#[derive(Debug, Args)]
struct SessionArgs {
    #[arg(long, env = "WISP_SESSION_ID")]
    session: String,
}

#[derive(Debug, Args)]
struct AcceptArgs {
    #[command(flatten)]
    session: SessionArgs,
    /// Accept AI ghost text instead of the selected dropdown candidate.
    #[arg(long)]
    ghost: bool,
    #[arg(long, value_enum, default_value_t = EditFormat::Zsh)]
    format: EditFormat,
}

#[derive(Debug, Args)]
struct ViewportArgs {
    #[arg(long, value_enum, default_value_t = ViewportFormat::Posix)]
    format: ViewportFormat,
}

#[derive(Debug, Args)]
struct DismissArgs {
    #[command(flatten)]
    session: SessionArgs,
    #[arg(long)]
    request_id: Option<u64>,
}

#[derive(Debug, Args)]
struct SessionArgsWithDirection {
    #[command(flatten)]
    session: SessionArgs,
    #[arg(value_enum)]
    direction: DirectionArg,
}

#[derive(Debug, Clone, Copy, ValueEnum)]
enum DirectionArg {
    Previous,
    Next,
}

#[derive(Debug, Clone, Copy, ValueEnum)]
enum ShellArg {
    Zsh,
    Bash,
    Fish,
    Nushell,
    Unknown,
}

#[derive(Debug, Clone, Copy, ValueEnum)]
enum CursorUnit {
    Characters,
    Bytes,
}

#[derive(Debug, Clone, Copy, ValueEnum)]
enum EditFormat {
    Zsh,
    Bash,
    Fish,
    Json,
}

#[derive(Debug, Clone, Copy, ValueEnum)]
enum ViewportFormat {
    Posix,
    Fish,
    Json,
}

#[derive(Debug, Clone, Copy, ValueEnum)]
enum TerminalArg {
    Auto,
    Alacritty,
    AppleTerminal,
    Iterm2,
    Ghostty,
    Wezterm,
    Kitty,
    Warp,
    Vscode,
    Unknown,
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let cli = Cli::parse();
    let socket = cli.socket.unwrap_or_else(default_socket_path);
    let config_path = cli.config.unwrap_or_else(default_config_path);
    match cli.command {
        CommandKind::Start => start(&socket, &config_path).await,
        CommandKind::Init { shell } => {
            let executable = std::env::current_exe().context("locate Wisp executable")?;
            let executable = executable.to_string_lossy();
            match shell {
                InitShell::Zsh => {
                    println!("typeset -gx WISP_BIN={}", posix_quote(&executable));
                    print!("{}", include_str!("../../../shells/wisp.plugin.zsh"));
                }
                InitShell::Bash => {
                    println!("export WISP_BIN={}", posix_quote(&executable));
                    print!("{}", include_str!("../../../shells/wisp.plugin.bash"));
                }
                InitShell::Fish => {
                    println!("set -gx WISP_BIN {}", fish_quote(&executable));
                    print!("{}", include_str!("../../../shells/wisp.plugin.fish"));
                }
                InitShell::Nushell => {
                    println!(
                        "$env.WISP_BIN = {}",
                        serde_json::to_string(executable.as_ref())?
                    );
                    print!("{}", include_str!("../../../shells/wisp.plugin.nu"));
                }
            }
            Ok(())
        }
        CommandKind::Shell { command } => shell_command(&socket, *command).await,
        CommandKind::Doctor => doctor(&socket, &config_path).await,
        CommandKind::Demo { buffer } => demo(&socket, buffer).await,
        CommandKind::Ping => {
            let response = request(&socket, ClientMessage::Ping).await?;
            if response != ServerMessage::Pong {
                bail!("unexpected daemon response: {response:?}");
            }
            println!("pong");
            Ok(())
        }
    }
}

async fn start(socket: &PathBuf, config_path: &Path) -> anyhow::Result<()> {
    let config = WispConfig::load(config_path)?;
    if request(socket, ClientMessage::Ping).await.is_err() {
        spawn_sibling("wisp-app", socket, config_path)?;
        let mut connected = false;
        for _ in 0..config.startup.attempts {
            tokio::time::sleep(Duration::from_millis(config.startup.retry_ms)).await;
            if request(socket, ClientMessage::Ping).await.is_ok() {
                connected = true;
                break;
            }
        }
        if !connected {
            bail!("wisp-app did not become ready at {}", socket.display());
        }
    }
    println!("Wisp is running. Load `wisp init <shell>` from your shell config.");
    Ok(())
}

fn spawn_sibling(name: &str, socket: &PathBuf, config: &Path) -> anyhow::Result<()> {
    let current = std::env::current_exe().context("locate current executable")?;
    let path = current.with_file_name(name);
    if !path.is_file() {
        bail!(
            "{} is not installed next to {}; run cargo build --workspace first",
            path.display(),
            current.display()
        );
    }
    let mut command = Command::new(path);
    command
        .env("WISP_SOCKET", socket)
        .arg("--config")
        .arg(config)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null());
    #[cfg(unix)]
    {
        use std::os::unix::process::CommandExt;
        command.process_group(0);
    }
    command.spawn().with_context(|| format!("start {name}"))?;
    Ok(())
}

async fn shell_command(socket: &PathBuf, command: ShellCommand) -> anyhow::Result<()> {
    match command {
        ShellCommand::Update(args) => {
            let no_wait = args.no_wait;
            let snapshot = snapshot_from_args(*args);
            let message = ClientMessage::Complete { snapshot };
            if no_wait {
                return send_only(socket, &message).await;
            }
            let response = request(socket, message).await?;
            if !matches!(response, ServerMessage::Render { .. }) {
                bail!("completion failed: {response:?}");
            }
        }
        ShellCommand::Navigate(args) => {
            let direction = match args.direction {
                DirectionArg::Previous => NavigationDirection::Previous,
                DirectionArg::Next => NavigationDirection::Next,
            };
            let response = request(
                socket,
                ClientMessage::Navigate {
                    session_id: args.session.session,
                    direction,
                },
            )
            .await?;
            if !matches!(response, ServerMessage::Render { .. }) {
                bail!("navigation is unavailable");
            }
        }
        ShellCommand::Accept(args) => {
            let target = if args.ghost {
                AcceptTarget::GhostText
            } else {
                AcceptTarget::Candidate
            };
            let response = request(
                socket,
                ClientMessage::Accept {
                    session_id: args.session.session,
                    target,
                },
            )
            .await?;
            let ServerMessage::ApplyEdit { edit } = response else {
                bail!("no suggestion to accept");
            };
            print_edit(&edit, args.format)?;
        }
        ShellCommand::Dismiss(args) => {
            let response = request(
                socket,
                ClientMessage::Dismiss {
                    session_id: args.session.session,
                    request_id: args.request_id,
                },
            )
            .await?;
            if !matches!(response, ServerMessage::Hidden { .. }) {
                bail!("dismiss failed: {response:?}");
            }
        }
        ShellCommand::Viewport(args) => print_zellij_viewport(args.format)?,
    }
    Ok(())
}

#[derive(Debug, Deserialize)]
struct ZellijPaneGeometry {
    id: u32,
    is_plugin: bool,
    is_focused: bool,
    tab_id: u32,
    pane_content_x: u16,
    pane_content_y: u16,
    pane_content_rows: u16,
    pane_content_columns: u16,
}

#[derive(Debug, Deserialize)]
struct ZellijTabGeometry {
    active: bool,
    tab_id: u32,
    display_area_rows: u16,
    display_area_columns: u16,
}

fn print_zellij_viewport(format: ViewportFormat) -> anyhow::Result<()> {
    if std::env::var_os("ZELLIJ").is_none() {
        bail!("not running inside zellij");
    }
    let panes_output = Command::new("zellij")
        .args([
            "action",
            "list-panes",
            "--all",
            "--geometry",
            "--state",
            "--tab",
            "--json",
        ])
        .output()
        .context("query zellij pane geometry")?;
    if !panes_output.status.success() {
        bail!(
            "zellij pane query failed: {}",
            String::from_utf8_lossy(&panes_output.stderr).trim()
        );
    }
    let tabs_output = Command::new("zellij")
        .args([
            "action",
            "list-tabs",
            "--all",
            "--dimensions",
            "--state",
            "--json",
        ])
        .output()
        .context("query zellij terminal geometry")?;
    if !tabs_output.status.success() {
        bail!(
            "zellij tab query failed: {}",
            String::from_utf8_lossy(&tabs_output.stderr).trim()
        );
    }

    let panes: Vec<ZellijPaneGeometry> =
        serde_json::from_slice(&panes_output.stdout).context("decode zellij panes")?;
    let tabs: Vec<ZellijTabGeometry> =
        serde_json::from_slice(&tabs_output.stdout).context("decode zellij tabs")?;
    let active_tab_id = tabs.iter().find(|tab| tab.active).map(|tab| tab.tab_id);
    let pane_id = std::env::var("ZELLIJ_PANE_ID")
        .ok()
        .and_then(|value| value.parse::<u32>().ok());
    let pane = pane_id
        .and_then(|pane_id| {
            panes
                .iter()
                .find(|pane| !pane.is_plugin && pane.id == pane_id)
        })
        .or_else(|| {
            panes.iter().find(|pane| {
                !pane.is_plugin && Some(pane.tab_id) == active_tab_id && pane.is_focused
            })
        })
        .context("could not identify the active zellij terminal pane")?;
    let tab = tabs
        .iter()
        .find(|tab| tab.tab_id == pane.tab_id)
        .context("could not identify the zellij pane's terminal grid")?;

    let values = [
        ("_WISP_VIEWPORT_X", pane.pane_content_x),
        ("_WISP_VIEWPORT_Y", pane.pane_content_y),
        ("_WISP_PANE_COLUMNS", pane.pane_content_columns),
        ("_WISP_PANE_ROWS", pane.pane_content_rows),
        ("_WISP_GRID_COLUMNS", tab.display_area_columns),
        ("_WISP_GRID_ROWS", tab.display_area_rows),
    ];
    match format {
        ViewportFormat::Posix => {
            for (name, value) in values {
                println!("{name}={value}");
            }
        }
        ViewportFormat::Fish => {
            for (name, value) in values {
                println!("set -g {name} {value}");
            }
        }
        ViewportFormat::Json => println!(
            "{}",
            serde_json::json!({
                "viewport_x": pane.pane_content_x,
                "viewport_y": pane.pane_content_y,
                "pane_columns": pane.pane_content_columns,
                "pane_rows": pane.pane_content_rows,
                "grid_columns": tab.display_area_columns,
                "grid_rows": tab.display_area_rows,
            })
        ),
    }
    Ok(())
}

fn snapshot_from_args(args: UpdateArgs) -> BufferSnapshot {
    let cursor = normalize_cursor(&args.buffer, args.cursor, args.cursor_unit);
    let terminal = match args.terminal {
        TerminalArg::Alacritty => TerminalKind::Alacritty,
        TerminalArg::AppleTerminal => TerminalKind::AppleTerminal,
        TerminalArg::Iterm2 => TerminalKind::Iterm2,
        TerminalArg::Ghostty => TerminalKind::Ghostty,
        TerminalArg::Wezterm => TerminalKind::Wezterm,
        TerminalArg::Kitty => TerminalKind::Kitty,
        TerminalArg::Warp => TerminalKind::Warp,
        TerminalArg::Vscode => TerminalKind::Vscode,
        TerminalArg::Unknown => TerminalKind::Unknown,
        TerminalArg::Auto => detect_terminal(),
    };
    let rendered =
        args.rendered_buffer
            .zip(args.rendered_cursor)
            .map(|(buffer, rendered_cursor)| {
                let rendered_cursor = normalize_cursor(&buffer, rendered_cursor, args.cursor_unit);
                RenderedCursorSnapshot {
                    buffer,
                    cursor: rendered_cursor,
                    prompt: args.rendered_prompt.unwrap_or_else(|| args.prompt.clone()),
                    columns: args.rendered_columns.unwrap_or(args.columns),
                }
            });
    let viewport = match (
        args.viewport_x,
        args.viewport_y,
        args.grid_columns,
        args.grid_rows,
    ) {
        (Some(x), Some(y), Some(grid_columns), Some(grid_rows))
            if grid_columns > 0 && grid_rows > 0 =>
        {
            Some(TerminalViewport {
                x,
                y,
                grid_columns,
                grid_rows,
            })
        }
        _ => None,
    };
    BufferSnapshot {
        request_id: args.request_id.unwrap_or_else(request_id),
        session_id: args.session,
        buffer: args.buffer,
        cursor,
        cwd: args.cwd,
        shell: match args.shell {
            ShellArg::Zsh => ShellKind::Zsh,
            ShellArg::Bash => ShellKind::Bash,
            ShellArg::Fish => ShellKind::Fish,
            ShellArg::Nushell => ShellKind::Nushell,
            ShellArg::Unknown => ShellKind::Unknown,
        },
        terminal: TerminalSnapshot {
            kind: terminal,
            window_id: args
                .window_id
                .filter(|value| !value.is_empty())
                .or_else(|| std::env::var("ALACRITTY_WINDOW_ID").ok()),
            columns: args.columns,
            rows: args.rows,
            prompt: args.prompt,
            cursor_row: args.cursor_row.and_then(|row| row.checked_sub(1)),
            cursor_column: args.cursor_column.and_then(|column| column.checked_sub(1)),
            rendered,
            viewport,
        },
    }
}

async fn doctor(socket: &PathBuf, config_path: &Path) -> anyhow::Result<()> {
    let config = WispConfig::load(config_path)?;
    println!("socket: {}", socket.display());
    match request(socket, ClientMessage::Ping).await {
        Ok(ServerMessage::Pong) => println!("daemon: ok"),
        _ => println!("daemon: not running"),
    }
    let terminal = detect_terminal();
    println!("terminal: {terminal:?}");
    let sample = BufferSnapshot {
        request_id: request_id(),
        session_id: "doctor".into(),
        buffer: "git ch".into(),
        cursor: 6,
        cwd: std::env::current_dir()?,
        shell: ShellKind::Zsh,
        terminal: TerminalSnapshot {
            kind: terminal,
            window_id: std::env::var("ALACRITTY_WINDOW_ID").ok(),
            columns: 80,
            rows: 24,
            prompt: "$ ".into(),
            cursor_row: None,
            cursor_column: None,
            rendered: None,
            viewport: None,
        },
    };
    match TerminalCursorLocator::from_config(&config.terminal).locate(&sample) {
        Ok(anchor) => println!(
            "cursor locator: ok ({:.1}, {:.1}); adjust WISP_<TERMINAL>_TITLEBAR/PADDING_X/PADDING_Y if needed",
            anchor.position.x, anchor.position.y
        ),
        Err(error) => println!("cursor locator: {error}"),
    }
    Ok(())
}

async fn demo(socket: &PathBuf, buffer: String) -> anyhow::Result<()> {
    let snapshot = BufferSnapshot {
        request_id: request_id(),
        session_id: "demo".into(),
        cursor: buffer.chars().count(),
        buffer,
        cwd: std::env::current_dir()?,
        shell: ShellKind::Zsh,
        terminal: TerminalSnapshot {
            kind: detect_terminal(),
            window_id: std::env::var("ALACRITTY_WINDOW_ID").ok(),
            columns: 80,
            rows: 24,
            prompt: "$ ".into(),
            cursor_row: None,
            cursor_column: None,
            rendered: None,
            viewport: None,
        },
    };
    let response = request(socket, ClientMessage::Complete { snapshot }).await?;
    println!("{}", serde_json::to_string_pretty(&response)?);
    Ok(())
}

async fn request(socket: &PathBuf, message: ClientMessage) -> anyhow::Result<ServerMessage> {
    let stream = UnixStream::connect(socket)
        .await
        .with_context(|| format!("connect to daemon at {}", socket.display()))?;
    let mut connection = framed(stream);
    send_message(&mut connection, &message).await?;
    receive_message(&mut connection)
        .await?
        .context("daemon closed the connection without a response")
}

async fn send_only(socket: &PathBuf, message: &ClientMessage) -> anyhow::Result<()> {
    let stream = UnixStream::connect(socket)
        .await
        .with_context(|| format!("connect to daemon at {}", socket.display()))?;
    let mut connection = framed(stream);
    send_message(&mut connection, message).await
}

fn detect_terminal() -> TerminalKind {
    let term_program = std::env::var("TERM_PROGRAM")
        .unwrap_or_default()
        .to_ascii_lowercase();
    let term = std::env::var("TERM")
        .unwrap_or_default()
        .to_ascii_lowercase();
    detect_terminal_from(&term_program, &term, |name| {
        std::env::var_os(name).is_some()
    })
}

fn normalize_cursor(buffer: &str, cursor: usize, unit: CursorUnit) -> usize {
    match unit {
        CursorUnit::Characters => cursor.min(buffer.chars().count()),
        CursorUnit::Bytes => {
            let mut byte = cursor.min(buffer.len());
            while !buffer.is_char_boundary(byte) {
                byte = byte.saturating_sub(1);
            }
            buffer[..byte].chars().count()
        }
    }
}

fn detect_terminal_from(
    term_program: &str,
    term: &str,
    has_environment_variable: impl Fn(&str) -> bool,
) -> TerminalKind {
    if has_environment_variable("ALACRITTY_SOCKET")
        || has_environment_variable("ALACRITTY_LOG")
        || term == "alacritty"
        || term_program == "alacritty"
    {
        TerminalKind::Alacritty
    } else if has_environment_variable("ITERM_SESSION_ID")
        || matches!(term_program, "iterm.app" | "iterm2")
    {
        TerminalKind::Iterm2
    } else if has_environment_variable("GHOSTTY_RESOURCES_DIR") || term_program.contains("ghostty")
    {
        TerminalKind::Ghostty
    } else if has_environment_variable("WEZTERM_PANE") || term_program.contains("wezterm") {
        TerminalKind::Wezterm
    } else if has_environment_variable("KITTY_WINDOW_ID")
        || term == "xterm-kitty"
        || term_program == "kitty"
    {
        TerminalKind::Kitty
    } else if has_environment_variable("WARP_IS_LOCAL_SHELL_SESSION")
        || term_program.contains("warp")
    {
        TerminalKind::Warp
    } else if has_environment_variable("VSCODE_INJECTION")
        || matches!(term_program, "vscode" | "code")
    {
        TerminalKind::Vscode
    } else if term_program == "apple_terminal" {
        TerminalKind::AppleTerminal
    } else {
        TerminalKind::Unknown
    }
}

fn print_edit(edit: &ApplyEdit, format: EditFormat) -> anyhow::Result<()> {
    let continue_completion = usize::from(edit.continue_completion);
    match format {
        EditFormat::Zsh => {
            println!("BUFFER={}", posix_quote(&edit.buffer));
            println!("CURSOR={}", edit.cursor);
            println!("WISP_CONTINUE={continue_completion}");
        }
        EditFormat::Bash => {
            println!("_WISP_EDIT_BUFFER={}", posix_quote(&edit.buffer));
            println!("_WISP_EDIT_CURSOR={}", edit.cursor);
            println!("_WISP_EDIT_CONTINUE={continue_completion}");
        }
        EditFormat::Fish => {
            println!("set -g _WISP_EDIT_BUFFER {}", fish_quote(&edit.buffer));
            println!("set -g _WISP_EDIT_CURSOR {}", edit.cursor);
            println!("set -g _WISP_EDIT_CONTINUE {continue_completion}");
        }
        EditFormat::Json => println!("{}", serde_json::to_string(edit)?),
    }
    Ok(())
}

fn posix_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

fn fish_quote(value: &str) -> String {
    format!("'{}'", value.replace('\\', "\\\\").replace('\'', "\\'"))
}

fn request_id() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos() as u64
}

fn default_socket_path() -> PathBuf {
    if let Some(path) = std::env::var_os("WISP_SOCKET") {
        return path.into();
    }
    std::env::var_os("XDG_RUNTIME_DIR").map_or_else(
        || std::env::temp_dir().join(format!("wisp-{}.sock", socket_identity())),
        |directory| PathBuf::from(directory).join("wisp.sock"),
    )
}

fn default_config_path() -> PathBuf {
    ProjectDirs::from("dev", "wisp", "wisp")
        .map(|dirs| dirs.config_dir().join("config.toml"))
        .unwrap_or_else(|| PathBuf::from("wisp.toml"))
}

fn socket_identity() -> String {
    std::env::var("USER")
        .unwrap_or_else(|_| "user".into())
        .chars()
        .filter(|ch| ch.is_ascii_alphanumeric() || *ch == '-')
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_common_terminals_from_their_standard_environment() {
        let cases = [
            (
                "Apple_Terminal",
                "xterm-256color",
                None,
                TerminalKind::AppleTerminal,
            ),
            ("iTerm.app", "xterm-256color", None, TerminalKind::Iterm2),
            ("ghostty", "xterm-ghostty", None, TerminalKind::Ghostty),
            ("WezTerm", "xterm-256color", None, TerminalKind::Wezterm),
            ("", "xterm-kitty", None, TerminalKind::Kitty),
            ("WarpTerminal", "xterm-256color", None, TerminalKind::Warp),
            ("vscode", "xterm-256color", None, TerminalKind::Vscode),
            (
                "",
                "xterm-256color",
                Some("ALACRITTY_SOCKET"),
                TerminalKind::Alacritty,
            ),
        ];
        for (program, term, variable, expected) in cases {
            assert_eq!(
                detect_terminal_from(&program.to_ascii_lowercase(), term, |name| {
                    variable == Some(name)
                }),
                expected
            );
        }
    }

    #[test]
    fn unrecognized_environment_uses_the_fallback_terminal_kind() {
        assert_eq!(
            detect_terminal_from("new-terminal", "xterm-256color", |_| false),
            TerminalKind::Unknown
        );
    }

    #[test]
    fn byte_cursors_are_normalized_to_protocol_character_offsets() {
        assert_eq!(normalize_cursor("a中🙂z", 0, CursorUnit::Bytes), 0);
        assert_eq!(normalize_cursor("a中🙂z", 1, CursorUnit::Bytes), 1);
        assert_eq!(normalize_cursor("a中🙂z", 4, CursorUnit::Bytes), 2);
        assert_eq!(normalize_cursor("a中🙂z", 8, CursorUnit::Bytes), 3);
        assert_eq!(normalize_cursor("a中🙂z", 99, CursorUnit::Bytes), 4);
    }

    #[test]
    fn byte_cursors_inside_a_codepoint_snap_to_its_start() {
        assert_eq!(normalize_cursor("a中z", 2, CursorUnit::Bytes), 1);
        assert_eq!(normalize_cursor("a中z", 3, CursorUnit::Bytes), 1);
    }

    #[test]
    fn shell_output_quoting_preserves_quotes_and_backslashes() {
        assert_eq!(posix_quote("a'b"), "'a'\\''b'");
        assert_eq!(fish_quote("a\\b'c"), "'a\\\\b\\'c'");
    }
}
