//! Packs every RON completion spec under `specs/` into one gzip container so the
//! binary can embed it and inflate documents on demand.

use std::{
    collections::BTreeMap,
    fs,
    io::Write,
    path::{Path, PathBuf},
};

use flate2::{Compression, write::GzEncoder};

/// The spec tree. A document's path below the root is its id, so
/// `az/2.53.0/network.ron` holds the spec `az/2.53.0/network`.
const SPEC_ROOT: &str = "specs";

fn main() {
    let workspace = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("workspace root must exist");

    let root = workspace.join(SPEC_ROOT);
    println!("cargo::rerun-if-changed={}", root.display());
    let mut specs: BTreeMap<String, PathBuf> = BTreeMap::new();
    collect(&root, &root, &mut specs);
    assert!(
        !specs.is_empty(),
        "no completion specs found under {SPEC_ROOT}/"
    );

    let mut pack = Vec::new();
    let mut index = String::from(
        "// @generated by build.rs -- (id, command, offset, length)\n\
         pub(crate) static SPEC_INDEX: &[(&str, &str, usize, usize)] = &[\n",
    );
    for (id, path) in &specs {
        let document = fs::read(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        let command = read_command(&document)
            .unwrap_or_else(|| panic!("no top-level `command` field in {}", path.display()));

        let offset = pack.len();
        let mut encoder = GzEncoder::new(&mut pack, Compression::default());
        encoder.write_all(&document).expect("compress spec");
        encoder.finish().expect("finish spec");
        index.push_str(&format!(
            "    ({:?}, {:?}, {}, {}),\n",
            id,
            command,
            offset,
            pack.len() - offset
        ));
    }
    index.push_str("];\n");

    let out = PathBuf::from(std::env::var_os("OUT_DIR").expect("cargo sets OUT_DIR"));
    fs::write(out.join("specs.ronpack"), &pack).expect("write spec pack");
    fs::write(out.join("spec_index.rs"), index).expect("write spec index");
}

fn collect(root: &Path, directory: &Path, specs: &mut BTreeMap<String, PathBuf>) {
    let entries =
        fs::read_dir(directory).unwrap_or_else(|e| panic!("read {}: {e}", directory.display()));
    for entry in entries {
        let path = entry.expect("read spec directory entry").path();
        if path.is_dir() {
            collect(root, &path, specs);
            continue;
        }
        if path.extension().and_then(|value| value.to_str()) != Some("ron") {
            continue;
        }
        let id = path
            .strip_prefix(root)
            .expect("spec must live below its root")
            .with_extension("")
            .to_str()
            .expect("spec path must be UTF-8")
            .to_owned();
        specs.insert(id, path);
    }
}

/// Reads the top-level `command` field without parsing the whole document --
/// the largest specs are several megabytes and only their id and command name
/// are needed at build time.
fn read_command(document: &[u8]) -> Option<String> {
    let head = std::str::from_utf8(document.get(..4096).unwrap_or(document)).ok()?;
    for line in head.lines() {
        let value = line.trim();
        if let Some(value) = value.strip_prefix("command:") {
            let value = value.trim().trim_end_matches(',').trim();
            return ron::from_str::<String>(value).ok();
        }
        if value.starts_with("subcommands:") || value.starts_with("options:") {
            break;
        }
    }
    None
}
