[package]
name = "wisp-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[build-dependencies]
flate2.workspace = true
ron.workspace = true

[dependencies]
anyhow.workspace = true
flate2.workspace = true
nucleo-matcher.workspace = true
ron.workspace = true
serde.workspace = true
serde_json.workspace = true
strip-ansi-escapes.workspace = true
tokio.workspace = true
tracing.workspace = true
unicode-width.workspace = true
wisp-protocol.workspace = true
