[package]
name = "wisp-app"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "wisp-app"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
directories.workspace = true
gpui.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
unicode-width.workspace = true
wisp-daemon = { path = "../wisp-daemon" }
wisp-protocol.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
cocoa.workspace = true
dispatch.workspace = true
objc.workspace = true
raw-window-handle.workspace = true
